#!/bin/bash
set -e

echo "Starting TYPO3 Blog Sync Docker Entrypoint..."

# Wait for database to be ready
echo "Waiting for database..."
until mysqladmin ping -h"typo3-db" -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" --silent --ssl=false; do
    echo "Database is unavailable - sleeping"
    sleep 2
done
echo "Database is ready!"

# Check if TYPO3 is already installed
if [ ! -f "/var/www/html/composer.json" ]; then
    echo "Installing TYPO3 ${TYPO3_VERSION}..."
    
    # Create TYPO3 project
    composer create-project typo3/cms-base-distribution:^${TYPO3_VERSION} /tmp/typo3-temp --no-interaction --no-dev
    
    # Move files to web root
    cp -r /tmp/typo3-temp/* /var/www/html/
    cp /tmp/typo3-temp/.gitignore /var/www/html/
    rm -rf /tmp/typo3-temp
    
    echo "TYPO3 installed successfully"
else
    echo "TYPO3 already installed, updating dependencies..."
    composer install --no-interaction --no-dev
fi

# Install blog extension if not present
if ! grep -q "t3g/blog" /var/www/html/composer.json; then
    echo "Installing TYPO3 Blog extension..."
    composer require t3g/blog:* --no-interaction --no-update
fi

# Register blog_sync as local path repository if not already done
if ! grep -q "agencypowerstack/blog-sync" /var/www/html/composer.json; then
    echo "Registering blog_sync extension via Composer..."
    composer config repositories.blog_sync path /var/www/html/packages/blog_sync
    composer require agencypowerstack/blog-sync:@dev --no-interaction --update-no-dev
fi

# Update composer dependencies
composer update --no-interaction --no-dev

# Set correct permissions (exclude read-only mounts)
chown -R www-data:www-data /var/www/html || true
chmod -R 755 /var/www/html || true

# Create necessary directories
mkdir -p /var/www/html/var/log
mkdir -p /var/www/html/var/charset
mkdir -p /var/www/html/public/fileadmin
mkdir -p /var/www/html/public/typo3temp
mkdir -p /var/www/html/public/uploads

chown -R www-data:www-data /var/www/html/var
chown -R www-data:www-data /var/www/html/public/fileadmin
chown -R www-data:www-data /var/www/html/public/typo3temp
chown -R www-data:www-data /var/www/html/public/uploads

# Prepare TYPO3 config directories for setup and backend-generated site configs
mkdir -p /var/www/html/config/system
mkdir -p /var/www/html/config/sites
chown -R www-data:www-data /var/www/html/config
chmod -R u+rwX,go+rX /var/www/html/config
find /var/www/html/config -type d -exec chmod 775 {} \;

# Create .htaccess if missing
if [ ! -f "/var/www/html/public/.htaccess" ]; then
    cat > /var/www/html/public/.htaccess <<'HTACCESS'
Options -Indexes
Options +FollowSymLinks

RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-l
RewriteRule ^(.*)$ index.php [QSA,L]
HTACCESS
    chown www-data:www-data /var/www/html/public/.htaccess
fi

# Run TYPO3 setup commands as www-data
echo "Running TYPO3 setup commands..."

if [ ! -f "/var/www/html/config/system/settings.php" ]; then
    su -s /bin/bash www-data -c "cd /var/www/html && php vendor/bin/typo3 setup --no-interaction --server-type=apache \
        --driver=mysqli --host=typo3-db --port=3306 \
        --dbname='${MYSQL_DATABASE}' --username='${MYSQL_USER}' --password='${MYSQL_PASSWORD}' \
        --admin-username='${TYPO3_ADMIN_USER:-admin}' \
        --admin-user-password='${TYPO3_ADMIN_PASSWORD}' \
        --admin-email='${TYPO3_ADMIN_EMAIL:-admin@example.com}' \
        --project-name='TYPO3 Blog Sync'"
else
    echo "TYPO3 already configured, skipping core setup"
fi

su -s /bin/bash www-data -c "cd /var/www/html && php vendor/bin/typo3 extension:setup -e blog"
su -s /bin/bash www-data -c "cd /var/www/html && php vendor/bin/typo3 extension:setup -e blog_sync"

# Prepare the autogenerated local site so frontend preview works out of the box.
mysql -h"typo3-db" -u"${MYSQL_USER}" -p"${MYSQL_PASSWORD}" --ssl=false "${MYSQL_DATABASE}" \
        -e "UPDATE pages SET hidden = 0, is_siteroot = 1 WHERE uid = 1 AND deleted = 0" || true

SITE_CONFIG=$(find /var/www/html/config/sites -name config.yaml | head -n 1 || true)
if [ -z "${SITE_CONFIG}" ]; then
        SITE_IDENTIFIER="local"
        SITE_DIR="/var/www/html/config/sites/${SITE_IDENTIFIER}"
        mkdir -p "${SITE_DIR}"
        SITE_CONFIG="${SITE_DIR}/config.yaml"
        BASE_URL="http://localhost:8090/"
else
        BASE_URL=$(awk -F"'" '/^base: / {print $2}' "${SITE_CONFIG}")
        if [ -z "${BASE_URL}" ]; then
                BASE_URL=$(awk -F'"' '/^base: / {print $2}' "${SITE_CONFIG}")
        fi
        if [ -z "${BASE_URL}" ]; then
                BASE_URL="http://localhost:8090/"
        fi
fi

cat > "${SITE_CONFIG}" <<EOF
base: '${BASE_URL}'
rootPageId: 1
languages:
    -
        title: English
        enabled: true
        languageId: 0
        base: /
        locale: en_US.UTF-8
        navigationTitle: English
        flag: us
imports:
    -
        resource: EXT:blog/Configuration/Routes/Default.yaml
dependencies:
    - blog/standalone
errorHandling: { }
routes: { }
EOF

chown -R www-data:www-data /var/www/html/config/sites

su -s /bin/bash www-data -c "cd /var/www/html && php vendor/bin/typo3 cache:flush" || true

echo "TYPO3 Blog Sync setup complete!"

# Execute CMD
exec "$@"
